version: '3.8'
services:
  application:
    image: "${IMAGE_NAME}"
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped